// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB210oHg-1ucc3t981b5VXG9PJMeZLIc-0',
    appId: '1:118562953389:web:6a8a639ee98b77d7c7ce24',
    messagingSenderId: '118562953389',
    projectId: 'fanari-84d40',
    authDomain: 'fanari-84d40.firebaseapp.com',
    storageBucket: 'fanari-84d40.appspot.com',
    measurementId: 'G-1G56H4VWZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WiB10U9zDHTeLsC76gmTNxNRuU_LbNo',
    appId: '1:118562953389:android:0b6c5e4ccaf7cbebc7ce24',
    messagingSenderId: '118562953389',
    projectId: 'fanari-84d40',
    storageBucket: 'fanari-84d40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNdS0DiY9NWBvOkFMGL4-p6Y-Zf0cvPIw',
    appId: '1:118562953389:ios:0b7cb3f6adefd6aec7ce24',
    messagingSenderId: '118562953389',
    projectId: 'fanari-84d40',
    storageBucket: 'fanari-84d40.appspot.com',
    iosBundleId: 'com.bitlaab.fanari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNdS0DiY9NWBvOkFMGL4-p6Y-Zf0cvPIw',
    appId: '1:118562953389:ios:0b7cb3f6adefd6aec7ce24',
    messagingSenderId: '118562953389',
    projectId: 'fanari-84d40',
    storageBucket: 'fanari-84d40.appspot.com',
    iosBundleId: 'com.bitlaab.fanari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB210oHg-1ucc3t981b5VXG9PJMeZLIc-0',
    appId: '1:118562953389:web:8b22cfaa154873d9c7ce24',
    messagingSenderId: '118562953389',
    projectId: 'fanari-84d40',
    authDomain: 'fanari-84d40.firebaseapp.com',
    storageBucket: 'fanari-84d40.appspot.com',
    measurementId: 'G-ZP08B9FL3E',
  );
}
